### PR TITLE
Add overarching story controller

### LINKED ISSUE #39: Add overarching story controller that controls transitioning between game phases
Add gdscript that controls switching the active script between:
 1. Introduction
 2. Story Scene 1
 3. Investigation Phase
 4. Conclusion Phase
 5. Win / Loss Screen

### PR DESCRIPTION
**Pull request by brydenli**
## Updates
* Move story controller logic from main.gd to a new StoryController AutoLoad script
* Add functions to handle active script switching for the remaining phases (conclusion, win/loss screen)
* Due to the linearity of the game phases, the story controller has been set up to handle active script switching accordingly (i.e. each scene transition function calls the next) 

Resolves #39

### CODE REVIEW

**Comment by ColinT** [comment]
Looks good, but I think we should keep the abstraction for selecting the initial scene as a configuration variable rather than within a function implementation.

**Review by ColinT — CHANGES_REQUESTED** [review]
See above comment

**Comment by brydenli** [comment]
> Looks good, but I think we should keep the abstraction for selecting the initial scene as a configuration variable rather than within a function implementation.

Updated 👍

**Review by anson-li — APPROVED** [review]
Approved, but would like to see this merged with the new win/loss screens developed by Jada to hit E2E.

**Review by ColinT — APPROVED** [review]

**Pull request merged**
