### PR TITLE
Added broken statue and rope to study

### PR DESCRIPTION
**Pull request by anson-li**
image

- Added rope and broken statue to study

### CODE REVIEW

**Comment by ColinT** [comment]
Statue model might have some normals facing the wrong direction:
image

**Review by ColinT — APPROVED** [review]
See comment on model above. If this is expected, then ignore.

**Comment by anson-li** [comment]
Thanks for the check, will fix before merging.

**Comment by anson-li** [comment]
image
Fixed, restarting your review

**Review by ColinT — APPROVED** [review]

**Review by brydenli — APPROVED** [review]

**Pull request merged**
