### PR TITLE
Add dialog to onclick events for wolf and iguana

### LINKED ISSUE #3: MVP: Dialog elements
Add clickable elements that bring up a dismissible dialog window with customizable text on it.

### PR DESCRIPTION
**Pull request by brydenli**
https://user-images.githubusercontent.com/73043856/200485433-661f3e48-b8ac-4c4a-9506-805a41378f42.mov

Resolves #3

### CODE REVIEW

**Comment by ColinT** [comment]
Not working in HTML5 preview. Try the fix here: https://github.com/coppolaemilio/dialogic/issues/898#issuecomment-1140508911

This issue should have been fixed in dialogic 1.4.3: https://github.com/coppolaemilio/dialogic/pull/978
Make sure your version is up to date or newer.

Also, change your tabs to spaces in your workspace settings.

**Review by ColinT — CHANGES_REQUESTED** [review]
Not working. See above.

**Comment by ColinT** [comment]
Possibly blocked by #14. Will revise the priority.

**Comment by ColinT** [comment]
Still not working, try the fix here: https://github.com/coppolaemilio/dialogic/tree/dialogic-1#-important

**Comment by brydenli** [comment]
> Still not working, try the fix here: https://github.com/coppolaemilio/dialogic/tree/dialogic-1#-important

That seemed to work 👍

**Review by ColinT — APPROVED** [review]

**Comment by ColinT** [comment]
lgtm

**Pull request merged**
